<?php
    // Set up page title:
    $this->headTitle($this->translate('My Profile'));

    // Set up breadcrumbs:
    $this->layout()->breadcrumbs = '<li><a href="' . $this->url('myresearch-home') . '">' . $this->transEsc('Your Account') . '</a></li> <li class="active">' . $this->transEsc('Profile') . '</li>';

    // Template for use by the renderArray helper:
    $arrTemplate = '<tr><th>%%LABEL%%:</th><td> %%VALUE%%</td></tr>';
?>

<a class="search-filter-toggle visible-xs" href="#myresearch-sidebar" data-toggle="offcanvas" title="Expand Sidebar">
  <?=$this->transEsc('Your Account') ?>
</a>

<div class="<?=$this->layoutClass('mainbody')?>">
  <h2><?=$this->transEsc('Your Profile')?></h2>
  <?=$this->flashmessages();?>
  <?php //print_r(empty($this->user['firstname'])); //empty=true, means value is available ?>
  <?php if(!empty($this->user['firstname']) && !empty($this->user['lastname']) && !empty($this->user['email'])){?>
    <?php
      // Define the value you want to save in the cookie
      $firstname = $this->user['firstname'];
      $lastname = $this->user['lastname'];
      $email2 = $this->user['email'];

      setcookie('firstname',$firstname,  time() + (86400 * 30), "/");           //30 days
      setcookie('lastname',$lastname,  time() + (86400 * 30), "/");           //30 days
      setcookie('email2',$email2,  time() + (86400 * 30), "/");           //30 days

      // Display a message or use the cookie value as needed
      // echo "Cookie value: '$firstname' , $lastname, $email2";
    ?>
    
  <table class="table table-striped">
    <?=$this->renderArray($arrTemplate,
          $this->user,
          [
              $this->transEsc('First Name') => 'firstname',
              $this->transEsc('Last Name') => 'lastname',
              $this->transEsc('Email') => 'email',
          ]
      );
    ?>
    <?php /* this section renders under two distinct circumstances; see if/else below: */ ?>
    <?php if (count($this->pickup ?? []) > 1 || !empty($this->preferredLibraryDisplay)): ?>
      <tr>
        <th><?=$this->transEsc('Preferred Library')?>:</th>
        <td>
          <?php if (count($this->pickup ?? []) > 1): // case 1: set home library allowed ?>
            <?php
              // Use ' ** ' for null ()
              $selected = $this->profile['home_library'] ?? ' ** ';
            ?>
            <form id="profile_form" class="form-inline" method="post">
              <select id="home_library" name="home_library" class="form-control">
                <option value=""<?='' === $selected ? ' selected="selected"' : ''?>>
                  <?=$this->transEsc('preferred_library_default')?>
                </option>
                <option value="<?=$this->escapeHtmlAttr(' ** ')?>"<?=' ** ' === $selected ? ' selected="selected"' : ''?>>
                  <?=$this->transEsc('Always ask me')?>
                </option>
                <?php foreach ($this->pickup as $lib): ?>
                  <option value="<?=$this->escapeHtmlAttr($lib['locationID'])?>"<?=($selected == $lib['locationID']) ? ' selected="selected"' : ''?>><?=$this->transEscWithPrefix('location_', $lib['locationDisplay'])?></option>
                <?php endforeach; ?>
              </select>
              <input class="btn btn-default" type="submit" value="<?=$this->transEscAttr('Save')?>">
            </form>
          <?php else: // case 2: set home library disallowed, but default provided by ILS ?>
            <?=$this->transEscWithPrefix('location_', $this->preferredLibraryDisplay)?>
          <?php endif; ?>
        </td>
      </tr>
    <?php endif; ?>
  </table>
  <?php } else {?>
    <?php
        // Define the value you want to save in the cookie
        $firstname = $this->user['firstname'];
        $lastname = $this->user['lastname'];
        $email2 = $this->user['email'];

        // Check if any of the variables are empty, and if so, set them to empty values
        if (empty($firstname)) {
          $firstname = "";
        }

        if (empty($lastname)) {
          $lastname = "";
        }

        if (empty($email2)) {
          $email2 = "";
        }

        // Set the cookies with the updated values
        setcookie('firstname', $firstname, time() + (86400 * 30), "/"); // 30 days
        setcookie('lastname', $lastname, time() + (86400 * 30), "/"); // 30 days
        setcookie('email2', $email2, time() + (86400 * 30), "/"); // 30 days

        // Display a message or use the cookie values as needed
        // echo "Cookie value: '$firstname' , $lastname, $email2";
      ?>
    <div class="modal fade" id="myModal" tabindex="-1" role="dialog" data-keyboard="false" data-backdrop="static">
          <div class="modal-dialog" role="document">
          <div class="modal-content">
              <div class="modal-header">
                <button type="button" class="btn-close closebtn" style="float: right;" data-lightbox data-dismiss="modal" aria-label="Close">X</button>
                <h4><?=$this->transEsc('Update User Details')?></h4>
              </div>
            <div class="modal-body">
              <div class="" > 
                <?=$this->flashmessages()?>
                <?php //echo $this->url('updateUserDetails',['id'=> $this->user['id']]); ?>
                <form method="post" name="form-profile" action="<?=$this->url('updateUserDetails',['id'=> $this->user['id']])?>" class="form-user-create" data-toggle="validator">
                  <div class="form-group hidden">
                    <label class="control-label" for="user_id"><?=$this->transEsc('UserID')?>:</label>
                    <input id="user_id" type="text" name="userid" value="<?=$this->escapeHtmlAttr($this->user['id'])?>" class="form-control" autocomplete="given-name">
                  </div>
                  <div class="form-group">
                    <label class="control-label" for="account_firstname"><?=$this->transEsc('First Name')?>:</label>
                    <input id="account_firstname" type="text" name="firstname" value="<?=$this->escapeHtmlAttr($this->user['firstname'])?>" class="form-control" autocomplete="given-name">
                  </div>
                  <div class="form-group">
                    <label class="control-label" for="account_lastname"><?=$this->transEsc('Last Name')?>:</label>
                    <input id="account_lastname" type="text" name="lastname" value="<?=$this->escapeHtmlAttr($this->user['lastname'])?>" class="form-control" autocomplete="family-name">
                  </div>
                  <div class="form-group">
                    <label class="control-label" for="account_email"><?=$this->transEsc('Email Address')?>:</label>
                    <input id="account_email" type="email" name="email" required aria-required="true" value="<?=$this->escapeHtmlAttr($this->user['email'])?>" class="form-control" autocomplete="email">
                    <div class="help-block with-errors"></div>
                  </div>
                  <div class="form-group">
                    <a class="back-to-login btn btn-link" href="<?=$this->url('myresearch-home') ?>"><?=$this->icon('page-prev') ?> <?=$this->transEsc('navigate_back')?></a>
                    <input class="btn btn-primary mx-5" type="submit" name="profiledetailsave" value="<?=$this->transEscAttr('Save user details')?>">
                    <button type="button" class="btn btn-default mx-5" data-dismiss="modal">Close</button>
                  </div>
                </form>             
              </div>
            </div>
            </div>
          </div>
        </div>
    <?php } ?>


  <div id="account-actions">
    <?php if ($this->auth()->getManager()->supportsEmailChange()): ?>
      <a class="btn btn-default icon-link" href="<?=$this->url('myresearch-changeemail') ?>">
        <?=$this->icon('profile-email', 'icon-link__icon') ?>
        <span class="icon-link__label"><?=$this->transEsc('Change Email Address') ?></span>
      </a>
    <?php endif; ?>

    <?php if ($this->auth()->getManager()->supportsPasswordChange()): ?>
      <a class="btn btn-default icon-link" href="<?=$this->url('myresearch-changepassword') ?>">
        <?=$this->icon('profile-change-password', 'icon-link__icon') ?>
        <span class="icon-link__label"><?=$this->transEsc('Change Password') ?></span>
      </a>
    <?php endif; ?>

    <?php if ($this->accountDeletion): ?>
      <a class="btn btn-default icon-link" href="<?=$this->url('myresearch-deleteaccount') ?>" data-lightbox>
        <?=$this->icon('profile-delete', 'icon-link__icon') ?>
        <span class="icon-link__label"><?=$this->transEsc('delete_account_title') ?></span>
      </a>
    <?php endif; ?>
  </div>

  <?php if (is_array($this->profile)): ?>
    <h3><?=$this->transEsc('Library Catalog Profile')?></h3>
    <p>
      <?=$this->context($this)->renderInContext('librarycards/selectcard.phtml', ['user' => $this->user]); ?>
    </p>
    <table class="table table-striped">
      <?=
        $this->renderArray(
            $arrTemplate,
            $this->profile,
            [
              $this->transEsc('First Name') => 'firstname',
              $this->transEsc('Last Name') => 'lastname',
              $this->transEsc('Address') . ' 1' => 'address1',
              $this->transEsc('Address') . ' 2' => 'address2',
              $this->transEsc('Zip') => 'zip',
              $this->transEsc('City') => 'city',
              $this->transEsc('Country') => 'country',
              $this->transEsc('Phone Number') => 'phone',
              $this->transEsc('Mobile Number') => 'mobile_phone',
              $this->transEsc('Group') => 'group',
              $this->transEsc('patron_account_expires') => 'expiration_date',
            ]
        );
      ?>
    </table>
  <?php elseif ('ils-none' !== $this->ils()->getOfflineMode() && $this->patronLoginView && !empty($this->patronLoginView->getTemplate())): ?>
    <?=$this->partial($this->patronLoginView);?>
  <?php endif; ?>
</div>

<div class="<?=$this->layoutClass('sidebar')?>" id="myresearch-sidebar">
  <?=$this->context($this)->renderInContext("myresearch/menu.phtml", ['active' => 'profile'])?>
</div>
